#!/usr/bin/env python

import signal
import sys
import time

def signal_handler(sig, frame):
    print('You pressed Ctrl+C!')
    sys.exit(0)


signal.signal(signal.SIGINT, signal_handler)

if len(sys.argv) != 2:
    print("usage: memory_free_space_test <number-of-megabytes>")
    sys.exit()

count = int(sys.argv[1])

megabyte = (0,) * (1024 * 1024 // 8)

data = megabyte * count

while True:
    time.sleep(1)
